### ISSUE TITLE
UI changes

### ISSUE THREAD

**Issue by stblr** [stblr/mkw-cs#9]
This is a tracking issue that lists all planned UI changes to have a clear overview of what's needed in terms of reverse-engineering and decompilation.

### Title (0x57)

- [ ] Add mkw-cs version number.
- [ ] Maybe add update options.

### License Selection (0x65)

- [ ] Remove grid of cup trophies.
- [ ] Extend to at least 6 licenses.
- [ ] Maybe change the friend code format.

### Single Player (0x69)

- [ ] Remove Grand Prix.
- [ ] Add new gamemodes (if any).

### Multiplayer (0x80)

- [ ] Add new gamemodes (if any).

### Solo/Team VS (0x72)

- [ ] Replace with VS rules.

### VS Rules (0x73)

- [ ] Add either a team size or a team count option (whatever is the most practical).
- [ ] Remove 50cc and 100cc, add 200cc and at least one mixed 150cc/mirror option.
- [ ] Add new item options (item rain in there maybe).
- [ ] Add player count option (more than 12 is not planned).

### Team Overview (0x74)

- [ ] Handle more than two teams.

### Vehicle Selection (0x6c, 0x81)

- [ ] Use real stats with different colors for vehicle and character parts.

### Cup/Course Selection (0x6e, 0x6f, 0x78, 0x79)

- [ ] Support custom tracks.
- [ ] Remove cups, use an alphabetically sorted course list instead.
- [ ] Add a course preview (image, minimap, version, creators).

### Race (0xc - 0x16)

- [ ] Rework the HUD with a speedometer, items held by teammates, spectator count.
- [ ] Show the HUD during ghost replay.

### Points Update (0x2f - 0x34)

- [ ] Handle more than 2 teams.

### Channel (0xa2)

- [ ] Remove Friends, Tournament and channel installation.
- [ ] Add Replays.

### Rankings (0xa3, 0xa8)

- [ ] Only keep top tens.
- [ ] Add filters.

### Replays (custom)

- [ ] History.
- [ ] By unique identifier (maybe re-use the "enter friend code" elements).

### Online (0x8b)

- [ ] Replace worldwides and regionals with some TBD "competitive" mode.
- [ ] Add Open Rooms.

### Open Rooms (custom)

- [ ] Room overview and detailed settings, stats, player list.
- [ ] Filters.

### Open Room Start (custom)

- [ ] Choose between VS, battle, potential custom gamemodes.
- [ ] Gamemode rules.
- [ ] Potential option to reduce waiting time between races.

### Friend Room (0x9d)

- [ ] Add gamemode rules.
- [ ] Kick players!

### Vote (0x92)

- [ ] Add ability to change character/vehicle.
- [ ] Always display timer, shorten it a bit.
